### ISSUE TITLE
Create Dataset from YAML file fails

### ISSUE THREAD

**Issue by scrumpmeister** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#10]
Tried to create a data set from the YAML file: https://raw.githubusercontent.com/ibm-wch/wch-openapi-documentation/master/wch_complete.yaml but it fails.

Reading the doc it states could be due to network latency, however that's not the case as I have the file local and also there's no option in the app to choose a non-local location.

**Comment by scrumpmeister** [comment]
Log file contains no information of listed YAML file error.

**Comment by PAnilReddy** [comment]
The network latency is not for the yaml file.
We use maven internally to generated the adapter from the given yaml and that downloads dependencies from web for the first time and this takes time.
There is a know issue and we are working towards it.
In the troubleshooting section, please follow the steps for now as mentioned in this section
"Failure to create a Data set for a Microservice using a swagger file."
After this runs successfully, you can start using it from UI

**Comment by PAnilReddy** [comment]
Hello, I just validated the YAML file which is given here.
Looks like there are validation error in the yaml and could be the reason for not generating the adapter and the same can be seen the log file.
The YAML file can be validated at https://editor.swagger.io/
some of errors shown are

Semantic error at definitions.Asset0.properties.renditions.items.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 1853

Semantic error at definitions.QueryResult0.properties.items.items.properties.renditions.items.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 1853

**Comment by chethankumar** [comment]
Closing it out for lack of activity. Please test the latest build and get back
