### ISSUE TITLE
Failed to fetch data source.

### ISSUE THREAD

**Issue by scrumpmeister** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#12]
Closed the Builder and re-opened, trying to add a new dataset - immediate error message windows appears with 'Failed to fetch data source'.  Closing or clicking OK causes a return to the dataset page so I'm in a loop.

**Comment by PAnilReddy** [comment]
Also you can find logs in the following location.
On mac OS: ~/Library/Logs/IBM Digital App Builder/log.log.
On Windows: %USERPROFILE%\AppData\Roaming\IBM Digital App Builder\log.log.

Please clear the log.log file in the above location and re-run the scenario and post the logs here. That will help us in understanding the problem

**Comment by ajaychebbi** [comment]
@scrumpmeister are you still facing the issue? Have you tried the GA build?

**Comment by chethankumar** [comment]
Closing it out for lack of activity. Please test the latest build and get back
