### ISSUE TITLE
IAM API Key authentication for chatbot and image recognition

### ISSUE THREAD

**Issue by hanneshoettinger** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#13]
Hi,

I am trying the App Builder and would like to connect the Watson Assistant service. However, the service uses IAM authentication with user:password. 
All the services switched to that authentication schema, however, if I would like to connect a service it is only possible using API Key + URL. 
Is there support for IAM authentication?

Thanks,
Hannes

**Comment by chethankumar** [comment]
Currently, we only support connecting to Watson Assistant using IAM API key and URL.

**Comment by hanneshoettinger** [comment]
Hey, 

thanks for the answer. But in the current version of Watson Assistant you have to connect with user and pass. API Key authentication is not possible anymore!?

What's your statement on that? Will you support the new authentication schema?

Thanks,
Hannes

**Comment by chethankumar** [comment]
Currently, when I try to create an instance of Watson Assistant, I do get the IAM API key and URL.
All Assistant instances will be migrated to IAM auth.
Which region are you creating the Watson assistant instance in?

**Comment by hanneshoettinger** [comment]
Thanks for the help. The Watson Assistant was an old instance that was not yet updated to the new authentication schema.
Hosting a new service resolved the issue!
