### ISSUE TITLE
App Creation & Preview issue on Windows 7

### ISSUE THREAD

**Issue by bmarolleau** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#14]
Hi ,  I've got errors when trying to create a new project/app ,  the prereqs (cordova, ionic, etc) are installed , in the system PATH....  2 errors, may be related: 
**Environment **  
npm  v6.5.0   ;  node v10.15.0  ;  ionic --version  4.7.1  cordova -v  8.1.2 (cordova-lib@8.1.1)

**1/ Error at project / app creation (web and pwa)**  Error in creating directory adapterGenerator
Info: Attempting to create App on Server.
Success: Project created on file system.
Info: Added app title to index.html
Info: Added bundle id to config.xml
Info: Copying over required plugins including mfp plugin.
Unzip start: 6:03:53 PM
Info: Copied over required node_modules
Info: Copied over required plugins.
Unzip finish: 6:05:01 PM
Installing dependencies and adding platform
Running npm install
stderr: Details The system cannot find the path specified.  
stderr: Error in creating directory adapterGenerator {"killed":false,"code":1,"signal":null,"cmd":"cd \"D:\\MobileApps\\app\\ibm\" && mkdir adapterGenerator"}
Error: Creating project failed 

**2/ Error when deploying / running app -**  <appfolder>\ionic\node_modules\@angular\core\package.json' Error: ENOENT: no such file or directory

Info: Updated mfp server url in config.xml.
Info: MFP server url updated is : https://mfp-sandbox.cloud.ibm.com
Info: Config.xml is updated
Info: Trying to shut down previous process
Info: Previous process is shutdown
stdout: √ Creating .\www directory for you - done! 
stdout: > cordova platform add browser --save 
stdout: Using cordova-fetch for cordova-browser@~5.0.1 
stdout: Adding browser project... 
stdout: Creating Cordova project for cordova-browser: Path: D:\MobileApps\app\ionic\platforms\browser 
stdout: Name: app 
stdout: Installing "cordova-plugin-device" for browser 
stdout: Installing "cordova-plugin-dialogs" for browser 
stdout: Installing "cordova-plugin-globalization" for browser 
stdout: Installing "cordova-plugin-ionic-keyboard" for browser 
stdout: Installing "cordova-plugin-ionic-webview" for browser 
stdout: Installing "cordova-plugin-mfp" for browser 
stdout: Plugin dependency "cordova-plugin-device@2.0.2" already fetched, using that version. 
stdout: Dependent plugin "cordova-plugin-device" already installed on browser. Plugin dependency "cordova-plugin-dialogs@2.0.1" already fetched, using that version. 
stdout: Dependent plugin "cordova-plugin-dialogs" already installed on browser. 
stdout: Plugin dependency "cordova-plugin-globalization@1.11.0" already fetched, using that version. 
stdout: Dependent plugin "cordova-plugin-globalization" already installed on browser. 
stdout: ***The run script is being replaced to suppress cordova's default browser.*** 
stdout: If you made changes to your run script(in cordova folder), manually merge run.bak with the run script that is provided with IBM MobileFirst Platform Foundation 
stdout: Installing "cordova-plugin-okhttp" for browser 
stdout: Installing "cordova-plugin-splashscreen" for browser 
stdout: Installing "cordova-plugin-statusbar" for browser 
stdout: Installing "cordova-plugin-whitelist" for browser 
stdout: Discovered plugin "cordova-plugin-advanced-http" in config.xml. Adding it to the project 
stdout: Installing "cordova-plugin-advanced-http" for browser 
stdout: Installing "cordova-plugin-file" for browser 
stdout: Adding cordova-plugin-advanced-http to package.json 
stdout: Saved plugin info for "cordova-plugin-advanced-http" to config.xml 
stdout: --save flag or autosave detected Saving browser@~5.0.4 into config.xml file ... 
stdout: > ionic-app-scripts build --target cordova --platform browser --port=8100 --no-interactive 
stdout: [18:08:08] ionic-app-scripts 3.2.1 
stdout: [18:08:08] build dev started ... 
stderr: [18:08:08] ionic-app-script task: "build" [18:08:08] Error: ENOENT: no such file or directory, open 'D:\MobileApps\app\ionic\node_modules\@angular\core\package.json' Error: ENOENT: no such file or directory, open 'D:\MobileApps\app\ionic\node_modules\@angular\core\package.json' 
stderr: [ERROR] An error occurred while running subprocess ionic-app-scripts. ionic-app-scripts build --target cordova --platform browser --port=8100 --no-int... exited with exit code 1. Re-running this command with the --verbose flag may provide more information. 
Error: Preview on Browser failed.

Any ideas?

**Comment by PAnilReddy** [comment]
For the first issue, it says not able to find the path in the system.
can you confirm of you have created the app in this location (D:\MobileApps\app).
and can you check if you have the following folder in this location(ibm and ionic).
Looks the app is not created correctly

**Comment by chethankumar** [comment]
You may also want to run the Digital App Builder as an Administrator to circumvent any permission issues.

**Comment by bmarolleau** [comment]
Hello,  indeed I had the same issue running as Administrator or not.  I confirm that the path specified at the application creation named "app" is D:\MobileApps\   , the folders ibm & ionic are created, populated: 
ibm contains adapterGenerator, data , watson folders .  and ionic contains node_modules, plaform, plugins, resources, src, www  + other files ; package.json etc.

**Comment by PAnilReddy** [comment]
Hello, I just validated the YAML file which is given here.
Looks like there are validation error in the yaml and could be the reason for not generating the adapter and the same can be seen the log file.
The YAML file can be validated at https://editor.swagger.io/
some of errors shown are 

Semantic error at definitions.Asset0.properties.renditions.items.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 1853

Semantic error at definitions.QueryResult0.properties.items.items.properties.renditions.items.required.0
Read only properties cannot be marked as required by a schema.
Jump to line 1853

**Comment by bmarolleau** [comment]
Here is the content of ionic/node_modules. 
![image](https://user-images.githubusercontent.com/19410995/51466019-887a5180-1d69-11e9-8244-acd59ce77c5c.png)
which explains the error when trying to run the app: 
stdout: > ionic-app-scripts build --target cordova --platform browser --port=8100 --no-interactive 
stdout: [10:41:01] ionic-app-scripts 3.2.1 
stdout: [10:41:01] build dev started ... 
stderr: [10:41:01] ionic-app-script task: "build" [10:41:01] Error: ENOENT: no such file or directory, open 'D:\MobileApps\FirstApp\ionic\node_modules\ionic-angular\package.json' Error: ENOENT: no such file or directory, open 'D:\MobileApps\FirstApp\ionic\node_modules\ionic-angular\package.json' 
stderr: [ERROR] An error occurred while running subprocess ionic-app-scripts. ionic-app-scripts build --target cordova --platform browser --port=8100 --no-int... exited with exit code 1. Re-running this command with the --verbose flag may provide more information. 
Error: Preview on Browser failed.

About the adapterGenerator folder , yes it is generated even if I receive the error message 
![image](https://user-images.githubusercontent.com/19410995/51466195-e60e9e00-1d69-11e9-93ff-02d0c828e7f8.png)

**Comment by bmarolleau** [comment]
![image](https://user-images.githubusercontent.com/19410995/51467038-dc863580-1d6b-11e9-99ff-37af0847e854.png)

**Comment by PAnilReddy** [comment]
Thank you for the investigation. We will try to figure out the problem.
yeah as you said Maven is needed for Adapter generation but its not a prereq, it is bundled with the project

**Comment by ajaychebbi** [comment]
@PAnilReddy is this fixed in GA? Or should we doc it?

**Comment by PAnilReddy** [comment]
I dont think its fixed, we will have to document it.

**Comment by hisubram** [comment]
added to troubleshooting section.
