### ISSUE TITLE
Server name is blanked out in settings after restarting the App builder

### ISSUE THREAD

**Issue by vivinkrishnan** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#20]
If I create a new project and chose shared server, settings show "mysharedserver". Thereafter , if I close the builder, open it and navigate to Settings -> Server for my project, the values are all blank, with servername greyed out. While I can fill all the other values, since server name is greyed out for editing, I cannot enter a value and hence cannot update.

![image](https://user-images.githubusercontent.com/11241339/53323390-0b13a500-3904-11e9-9bf5-d9c2f5a5dfe7.png)

Environment:
v0.91.2 for Mac ( and Windows).

https://developer.ibm.com/answers/questions/494260/why-is-server-name-is-grayed-out-in-settings-for-i.html?utm_campaign=answers&utm_medium=email&utm_source=answers-new-question&utm_content=answers-answer-question

**Comment by jjayabal** [comment]
Server settings page is revamped now. Pls check in the next available version.

**Comment by ajaychebbi** [comment]
Fixed in GA
