### ISSUE TITLE
Prerequisite Check Fails for Android Studio Even When Installed

### ISSUE THREAD

**Issue by RosewaterDevelopmentLLC** [MobileFirst-Platform-Developer-Center/Digital-App-Builder#21]
Prerequisite Check Fails for Android Studio Even When Installed

**Comment by chethankumar** [comment]
We actually check for adb being the path when we say Android Studio. If you add the location to adb to the path, it should reflect in the Prerequisite check.

**Comment by RosewaterDevelopmentLLC** [comment]
It is now in the path, can be executed from CMD, but App Builder prereq check still does not recognize it

**Comment by jjayabal** [comment]
Could you please have android executable (../Sdk/tools) in the path and check it.

**Comment by RosewaterDevelopmentLLC** [comment]
Thank You.  Please have someone address issue#23

**Comment by ajaychebbi** [comment]
Please add this to documentation

**Comment by hisubram** [comment]
added in troubleshooting.
